const baseWords = [
 // A
 { en: "a", tr: "Bir", lvl: "A1", cat: "Artikel" },
  { en: "an", tr: "Bir", lvl: "A1", cat: "Artikel" },
  { en: "ability", tr: "Yetenek", lvl: "A2", cat: "İsim" },
  { en: "able", tr: "Yapabilen", lvl: "A2", cat: "Sıfat" },
  { en: "about", tr: "Hakkında", lvl: "A1", cat: "Edat" },
  { en: "accept", tr: "Kabul Etmek", lvl: "A2", cat: "Fiil" },
  { en: "accident", tr: "Kaza", lvl: "A1", cat: "İsim" },
  { en: "by accident", tr: "Kazayla", lvl: "A2", cat: "Zarf" },
  { en: "across", tr: "Karşısında", lvl: "A1", cat: "Edat" },
  { en: "act", tr: "Davranmak", lvl: "A2", cat: "Fiil" },
  { en: "action", tr: "Eylem", lvl: "A2", cat: "İsim" },
  { en: "activity", tr: "Aktivite", lvl: "A1", cat: "İsim" },
  { en: "add", tr: "Eklemek", lvl: "A1", cat: "Fiil" },
  { en: "address", tr: "Adres", lvl: "A1", cat: "İsim" },
  { en: "adjective", tr: "Sıfat", lvl: "A1", cat: "Dilbilgisi" },
  { en: "advantage", tr: "Avantaj", lvl: "A2", cat: "İsim" },
  { en: "aerial", tr: "Havadan", lvl: "B1", cat: "Sıfat" },
  { en: "aeroplane", tr: "Uçak", lvl: "A1", cat: "Araç" },
  { en: "afraid", tr: "Korkmuş", lvl: "A1", cat: "Duygu" },
  { en: "after", tr: "Sonra", lvl: "A1", cat: "Zaman" },
  { en: "afternoon", tr: "Öğleden Sonra", lvl: "A1", cat: "Zaman" },
  { en: "again", tr: "Tekrar", lvl: "A1", cat: "Zarf" },
  { en: "against", tr: "Karşı", lvl: "A2", cat: "Edat" },
  { en: "age", tr: "Yaş", lvl: "A1", cat: "İsim" },
  { en: "ago", tr: "Önce", lvl: "A1", cat: "Zaman" },
  { en: "agree", tr: "Katılmak", lvl: "A1", cat: "Fiil" },
  { en: "air", tr: "Hava", lvl: "A1", cat: "Doğa" },
  { en: "air-conditioner", tr: "Klima", lvl: "A1", cat: "Eşya" },
  { en: "airline", tr: "Havayolu Şirketi", lvl: "A2", cat: "Ulaşım" },
  { en: "airplane", tr: "Uçak", lvl: "A1", cat: "Araç" },
  { en: "alike", tr: "Benzer", lvl: "B1", cat: "Sıfat" },
  { en: "alive", tr: "Canlı", lvl: "A2", cat: "Sıfat" },
  { en: "all", tr: "Hepsi", lvl: "A1", cat: "Zamir" },
  { en: "all right", tr: "Tamam", lvl: "A1", cat: "İfade" },
  { en: "allow", tr: "İzin Vermek", lvl: "A2", cat: "Fiil" },
  { en: "almost", tr: "Neredeyse", lvl: "A1", cat: "Zarf" },
  { en: "alone", tr: "Yalnız", lvl: "A1", cat: "Sıfat" },
  { en: "along", tr: "Boyunca", lvl: "A2", cat: "Edat" },
  { en: "aloud", tr: "Sesli Olarak", lvl: "A2", cat: "Zarf" },
  { en: "alphabet", tr: "Alfabe", lvl: "A1", cat: "Dil" },
  { en: "also", tr: "Ayrıca", lvl: "A1", cat: "Zarf" },
  { en: "always", tr: "Her Zaman", lvl: "A1", cat: "Zarf" },
  { en: "among", tr: "Arasında", lvl: "A2", cat: "Edat" },
  { en: "and", tr: "Ve", lvl: "A1", cat: "Bağlaç" },
  { en: "angry", tr: "Kızgın", lvl: "A1", cat: "Duygu" },
  { en: "animal", tr: "Hayvan", lvl: "A1", cat: "Canlı" },
  { en: "another", tr: "Başka", lvl: "A1", cat: "Belirteç" },
  { en: "answer", tr: "Cevap", lvl: "A1", cat: "İsim" },
  { en: "ant", tr: "Karınca", lvl: "A1", cat: "Hayvan" },
  { en: "any", tr: "Herhangi", lvl: "A1", cat: "Belirteç" },
  { en: "anybody", tr: "Herhangi Biri", lvl: "A1", cat: "Zamir" },
  { en: "anyone", tr: "Herhangi Biri", lvl: "A1", cat: "Zamir" },
  { en: "anything", tr: "Herhangi Bir Şey", lvl: "A1", cat: "Zamir" },
  { en: "anywhere", tr: "Herhangi Bir Yer", lvl: "A1", cat: "Zarf" },
  { en: "apple", tr: "Elma", lvl: "A1", cat: "Meyve" },
  { en: "aprikot", tr: "Kayısı", lvl: "A1", cat: "Meyve" },
  { en: "april", tr: "Nisan", lvl: "A1", cat: "Zaman" },
  { en: "are", tr: "Olmak (çoğul)", lvl: "A1", cat: "Fiil" },
  { en: "arm", tr: "Kol", lvl: "A1", cat: "Vücut" },
  { en: "armchair", tr: "Koltuk", lvl: "A1", cat: "Eşya" },
  { en: "army", tr: "Ordu", lvl: "A2", cat: "Toplum" },
  { en: "around", tr: "Etrafında", lvl: "A1", cat: "Edat" },
  { en: "as", tr: "Gibi / Olarak", lvl: "A1", cat: "Bağlaç" },
  { en: "as ... as", tr: "Kadar", lvl: "A1", cat: "Yapı" },
  { en: "ask", tr: "Sormak", lvl: "A1", cat: "Fiil" },
  { en: "at", tr: "-de / -da", lvl: "A1", cat: "Edat" },
  { en: "attention", tr: "Dikkat", lvl: "A2", cat: "İsim" },
  { en: "august", tr: "Ağustos", lvl: "A1", cat: "Zaman" },
  { en: "aunt", tr: "Teyze / Hala", lvl: "A1", cat: "Aile" },
  { en: "automobile", tr: "Otomobil", lvl: "A2", cat: "Araç" },
  { en: "autumn", tr: "Sonbahar", lvl: "A1", cat: "Mevsim" },
  { en: "awake", tr: "Uyanık", lvl: "A2", cat: "Sıfat" },
  { en: "away", tr: "Uzakta", lvl: "A1", cat: "Zarf" },

  // B
   { en: "baby", tr: "Bebek", lvl: "A1", cat: "İnsan" },
  { en: "back", tr: "Sırt / Geri", lvl: "A1", cat: "Yön" },
  { en: "bad", tr: "Kötü", lvl: "A1", cat: "Sıfat" },
  { en: "bag", tr: "Çanta", lvl: "A1", cat: "Eşya" },
  { en: "baggage", tr: "Bagaj", lvl: "A1", cat: "Seyahat" },
  { en: "balcony", tr: "Balkon", lvl: "A1", cat: "Yer" },
  { en: "ball", tr: "Top", lvl: "A1", cat: "Spor" },
  { en: "balloon", tr: "Balon", lvl: "A1", cat: "Eşya" },
  { en: "banana", tr: "Muz", lvl: "A1", cat: "Meyve" },
  { en: "bank", tr: "Banka", lvl: "A1", cat: "Yer" },
  { en: "bar", tr: "Bar", lvl: "A1", cat: "Yer" },
  { en: "barber", tr: "Berber", lvl: "A1", cat: "Meslek" },
  { en: "basic", tr: "Temel", lvl: "A2", cat: "Sıfat" },
  { en: "basket", tr: "Sepet", lvl: "A1", cat: "Eşya" },
  { en: "basketball", tr: "Basketbol", lvl: "A1", cat: "Spor" },
  { en: "bathroom", tr: "Banyo", lvl: "A1", cat: "Yer" },
  { en: "be", tr: "Olmak", lvl: "A1", cat: "Fiil" },
  { en: "bear", tr: "Ayı", lvl: "A1", cat: "Hayvan" },
  { en: "beautiful", tr: "Güzel", lvl: "A1", cat: "Sıfat" },
  { en: "because", tr: "Çünkü", lvl: "A1", cat: "Bağlaç" },
  { en: "become", tr: "Olmak / Haline Gelmek", lvl: "A2", cat: "Fiil" },
  { en: "bed", tr: "Yatak", lvl: "A1", cat: "Eşya" },
  { en: "bedroom", tr: "Yatak Odası", lvl: "A1", cat: "Yer" },
  { en: "before", tr: "Önce", lvl: "A1", cat: "Zaman" },
  { en: "begin", tr: "Başlamak", lvl: "A1", cat: "Fiil" },
  { en: "beginning", tr: "Başlangıç", lvl: "A2", cat: "İsim" },
  { en: "behind", tr: "Arkasında", lvl: "A1", cat: "Edat" },
  { en: "believe", tr: "İnanmak", lvl: "A2", cat: "Fiil" },
  { en: "best", tr: "En İyi", lvl: "A1", cat: "Sıfat" },
  { en: "better", tr: "Daha İyi", lvl: "A1", cat: "Sıfat" },
  { en: "between", tr: "Arasında", lvl: "A1", cat: "Edat" },
  { en: "big", tr: "Büyük", lvl: "A1", cat: "Sıfat" },
  { en: "bill", tr: "Fatura", lvl: "A1", cat: "Para" },
  { en: "bird", tr: "Kuş", lvl: "A1", cat: "Hayvan" },
  { en: "birthday", tr: "Doğum Günü", lvl: "A1", cat: "Zaman" },
  { en: "biscuit", tr: "Bisküvi", lvl: "A1", cat: "Yiyecek" },
  { en: "bite", tr: "Isırmak", lvl: "A2", cat: "Fiil" },
  { en: "black", tr: "Siyah", lvl: "A1", cat: "Renk" },
  { en: "blackboard", tr: "Kara Tahta", lvl: "A1", cat: "Eğitim" },
  { en: "blanket", tr: "Battaniye", lvl: "A1", cat: "Eşya" },
  { en: "blood", tr: "Kan", lvl: "A2", cat: "Vücut" },
  { en: "blue", tr: "Mavi", lvl: "A1", cat: "Renk" },
  { en: "boat", tr: "Tekne", lvl: "A1", cat: "Araç" },
  { en: "body", tr: "Vücut", lvl: "A1", cat: "Vücut" },
  { en: "book", tr: "Kitap", lvl: "A1", cat: "Eşya" },
  { en: "bookshop", tr: "Kitapçı", lvl: "A1", cat: "Yer" },
  { en: "born", tr: "Doğmuş", lvl: "A1", cat: "Fiil" },
  { en: "both", tr: "İkisi de", lvl: "A1", cat: "Belirteç" },
  { en: "bottle", tr: "Şişe", lvl: "A1", cat: "Eşya" },
  { en: "box", tr: "Kutu", lvl: "A1", cat: "Eşya" },
  { en: "boy", tr: "Erkek Çocuk", lvl: "A1", cat: "İnsan" },
  { en: "branch", tr: "Dal", lvl: "A2", cat: "Doğa" },
  { en: "bread", tr: "Ekmek", lvl: "A1", cat: "Yiyecek" },
  { en: "break", tr: "Kırmak", lvl: "A1", cat: "Fiil" },
  { en: "break down", tr: "Bozulmak", lvl: "A2", cat: "Fiil" },
  { en: "breakfast", tr: "Kahvaltı", lvl: "A1", cat: "Yiyecek" },
  { en: "bring", tr: "Getirmek", lvl: "A1", cat: "Fiil" },
  { en: "brother", tr: "Erkek Kardeş", lvl: "A1", cat: "Aile" },
  { en: "brown", tr: "Kahverengi", lvl: "A1", cat: "Renk" },
  { en: "brush", tr: "Fırça", lvl: "A1", cat: "Eşya" },
  { en: "bucket", tr: "Kova", lvl: "A1", cat: "Eşya" },
  { en: "build", tr: "İnşa Etmek", lvl: "A2", cat: "Fiil" },
  { en: "building", tr: "Bina", lvl: "A1", cat: "Yer" },
  { en: "bus", tr: "Otobüs", lvl: "A1", cat: "Araç" },
  { en: "business", tr: "İş", lvl: "A2", cat: "Ekonomi" },
  { en: "businessman", tr: "İş Adamı", lvl: "A1", cat: "Meslek" },
  { en: "busy", tr: "Meşgul", lvl: "A1", cat: "Sıfat" },
  { en: "but", tr: "Ama", lvl: "A1", cat: "Bağlaç" },
  { en: "butcher's", tr: "Kasap", lvl: "A1", cat: "Yer" },
  { en: "butter", tr: "Tereyağı", lvl: "A1", cat: "Yiyecek" },
  { en: "buy", tr: "Satın Almak", lvl: "A1", cat: "Fiil" },
  { en: "by", tr: "Tarafından / İle", lvl: "A1", cat: "Edat" },
  { en: "bye", tr: "Hoşça Kal", lvl: "A1", cat: "İfade" },

  // C
  { en: "cafe", tr: "Kafe", lvl: "A1", cat: "Yer" },
  { en: "cafeteria", tr: "Kafeterya", lvl: "A1", cat: "Yer" },
  { en: "cake", tr: "Kek", lvl: "A1", cat: "Yiyecek" },
  { en: "calendar", tr: "Takvim", lvl: "A1", cat: "Zaman" },
  { en: "call", tr: "Aramak / Çağırmak", lvl: "A1", cat: "Fiil" },
  { en: "camera", tr: "Kamera", lvl: "A1", cat: "Eşya" },
  { en: "can", tr: "-ebilmek", lvl: "A1", cat: "Modal Fiil" },
  { en: "capital", tr: "Başkent / Sermaye", lvl: "A1", cat: "Yer" },
  { en: "car", tr: "Araba", lvl: "A1", cat: "Araç" },
  { en: "card", tr: "Kart", lvl: "A1", cat: "Eşya" },
  { en: "careful", tr: "Dikkatli", lvl: "A1", cat: "Sıfat" },
  { en: "carpet", tr: "Halı", lvl: "A1", cat: "Eşya" },
  { en: "carrot", tr: "Havuç", lvl: "A1", cat: "Sebze" },
  { en: "carry", tr: "Taşımak", lvl: "A1", cat: "Fiil" },
  { en: "cashier", tr: "Kasiyer", lvl: "A1", cat: "Meslek" },
  { en: "cat", tr: "Kedi", lvl: "A1", cat: "Hayvan" },
  { en: "catch", tr: "Yakalamak", lvl: "A2", cat: "Fiil" },
  { en: "ceiling", tr: "Tavan", lvl: "A1", cat: "Yer" },
  { en: "center", tr: "Merkez", lvl: "A1", cat: "Yer" },
  { en: "central", tr: "Merkezi", lvl: "A2", cat: "Sıfat" },
  { en: "certain", tr: "Kesin / Belirli", lvl: "A2", cat: "Sıfat" },
  { en: "certainly", tr: "Kesinlikle", lvl: "A2", cat: "Zarf" },
  { en: "chair", tr: "Sandalye", lvl: "A1", cat: "Eşya" },
  { en: "chalk", tr: "Tebeşir", lvl: "A1", cat: "Eğitim" },
  { en: "chance", tr: "Şans / Olasılık", lvl: "A2", cat: "İsim" },
  { en: "change", tr: "Değiştirmek / Değişim", lvl: "A1", cat: "Fiil" },
  { en: "character", tr: "Karakter", lvl: "A2", cat: "İsim" },
  { en: "cheap", tr: "Ucuz", lvl: "A1", cat: "Sıfat" },
  { en: "check", tr: "Kontrol Etmek", lvl: "A1", cat: "Fiil" },
  { en: "cheek", tr: "Yanak", lvl: "A1", cat: "Vücut" },
  { en: "cheerful", tr: "Neşeli", lvl: "A1", cat: "Duygu" },
  { en: "cheese", tr: "Peynir", lvl: "A1", cat: "Yiyecek" },
  { en: "chemist's", tr: "Eczane", lvl: "A1", cat: "Yer" },
  { en: "chess", tr: "Satranç", lvl: "A1", cat: "Oyun" },
  { en: "chicken", tr: "Tavuk", lvl: "A1", cat: "Hayvan" },
  { en: "child", tr: "Çocuk", lvl: "A1", cat: "İnsan" },
  { en: "chips", tr: "Patates Kızartması", lvl: "A1", cat: "Yiyecek" },
  { en: "chocolate", tr: "Çikolata", lvl: "A1", cat: "Yiyecek" },
  { en: "choose", tr: "Seçmek", lvl: "A1", cat: "Fiil" },
  { en: "church", tr: "Kilise", lvl: "A1", cat: "Yer" },
  { en: "cigarette", tr: "Sigara", lvl: "A1", cat: "Ürün" },
  { en: "cinema", tr: "Sinema", lvl: "A1", cat: "Yer" },
  { en: "city", tr: "Şehir", lvl: "A1", cat: "Yer" },
  { en: "class", tr: "Sınıf / Ders", lvl: "A1", cat: "Eğitim" },
  { en: "classroom", tr: "Sınıf", lvl: "A1", cat: "Eğitim" },
  { en: "clean", tr: "Temiz / Temizlemek", lvl: "A1", cat: "Fiil" },
  { en: "clear", tr: "Açık / Net", lvl: "A2", cat: "Sıfat" },
  { en: "clearly", tr: "Açıkça", lvl: "A2", cat: "Zarf" },
  { en: "close", tr: "Kapatmak / Yakın", lvl: "A1", cat: "Fiil" },
  { en: "closed", tr: "Kapalı", lvl: "A1", cat: "Sıfat" },
  { en: "cloud", tr: "Bulut", lvl: "A1", cat: "Doğa" },
  { en: "cloudy", tr: "Bulutlu", lvl: "A1", cat: "Hava" },
  { en: "coffee", tr: "Kahve", lvl: "A1", cat: "İçecek" },
  { en: "coke", tr: "Kola", lvl: "A1", cat: "İçecek" },
  { en: "cola", tr: "Kola", lvl: "A1", cat: "İçecek" },
  { en: "cold", tr: "Soğuk", lvl: "A1", cat: "Sıfat" },
  { en: "collect", tr: "Toplamak", lvl: "A2", cat: "Fiil" },
  { en: "college", tr: "Kolej", lvl: "A1", cat: "Eğitim" },
  { en: "colour", tr: "Renk", lvl: "A1", cat: "İsim" },
  { en: "comb", tr: "Tarak", lvl: "A1", cat: "Eşya" },
  { en: "come", tr: "Gelmek", lvl: "A1", cat: "Fiil" },
  { en: "company", tr: "Şirket", lvl: "A1", cat: "İş" },
  { en: "competition", tr: "Yarışma", lvl: "A2", cat: "İsim" },
  { en: "completely", tr: "Tamamen", lvl: "A2", cat: "Zarf" },
  { en: "computer", tr: "Bilgisayar", lvl: "A1", cat: "Teknoloji" },
  { en: "condition", tr: "Durum / Şart", lvl: "B1", cat: "İsim" },
  { en: "continue", tr: "Devam Etmek", lvl: "A2", cat: "Fiil" },
  { en: "control", tr: "Kontrol Etmek", lvl: "A2", cat: "Fiil" },
  { en: "conversation", tr: "Konuşma", lvl: "A2", cat: "İletişim" },
  { en: "copy", tr: "Kopya", lvl: "A1", cat: "Fiil" },
  { en: "corner", tr: "Köşe", lvl: "A1", cat: "Yer" },
  { en: "cornflakes", tr: "Mısır Gevreği", lvl: "A1", cat: "Yiyecek" },
  { en: "correct", tr: "Doğru", lvl: "A1", cat: "Sıfat" },
  { en: "cost", tr: "Ücret / Mal Olmak", lvl: "A1", cat: "Fiil" },
  { en: "cotton", tr: "Pamuk", lvl: "A1", cat: "Madde" },
  { en: "cough", tr: "Öksürmek", lvl: "A1", cat: "Fiil" },
  { en: "could", tr: "-ebilirdi", lvl: "A1", cat: "Modal Fiil" },
  { en: "could you", tr: "Rica İfadesi", lvl: "A1", cat: "İfade" },
  { en: "count", tr: "Saymak", lvl: "A1", cat: "Fiil" },
  { en: "country", tr: "Ülke", lvl: "A1", cat: "Yer" },
  { en: "cover", tr: "Kaplamak", lvl: "A2", cat: "Fiil" },
  { en: "cow", tr: "İnek", lvl: "A1", cat: "Hayvan" },
  { en: "cream", tr: "Krema", lvl: "A1", cat: "Yiyecek" },
  { en: "cucumber", tr: "Salatalık", lvl: "A1", cat: "Sebze" },
  { en: "cup", tr: "Fincan", lvl: "A1", cat: "Eşya" },
  { en: "customer", tr: "Müşteri", lvl: "A1", cat: "İnsan" },
  { en: "cut", tr: "Kesmek", lvl: "A1", cat: "Fiil" },

  // D
    { en: "dad", tr: "Baba", lvl: "A1", cat: "Aile" },
  { en: "daily", tr: "Günlük", lvl: "A1", cat: "Zaman" },
  { en: "dark", tr: "Karanlık", lvl: "A1", cat: "Sıfat" },
  { en: "data", tr: "Veri", lvl: "A2", cat: "Bilgi" },
  { en: "date", tr: "Tarih / Randevu", lvl: "A1", cat: "Zaman" },
  { en: "daughter", tr: "Kız evlat", lvl: "A1", cat: "Aile" },
  { en: "day", tr: "Gün", lvl: "A1", cat: "Zaman" },
  { en: "dead", tr: "Ölü", lvl: "A1", cat: "Sıfat" },
  { en: "dear", tr: "Sevgili / Değerli", lvl: "A1", cat: "Sıfat" },
  { en: "death", tr: "Ölüm", lvl: "A2", cat: "İsim" },
  { en: "december", tr: "Aralık", lvl: "A1", cat: "Zaman" },
  { en: "decide", tr: "Karar Vermek", lvl: "A1", cat: "Fiil" },
  { en: "deep", tr: "Derin", lvl: "A1", cat: "Sıfat" },
  { en: "dentist", tr: "Diş Hekimi", lvl: "A1", cat: "Meslek" },
  { en: "dialogue", tr: "Diyalog", lvl: "A2", cat: "İletişim" },
  { en: "dictionary", tr: "Sözlük", lvl: "A1", cat: "Eğitim" },
  { en: "difference", tr: "Fark", lvl: "A2", cat: "İsim" },
  { en: "different", tr: "Farklı", lvl: "A1", cat: "Sıfat" },
  { en: "difficult", tr: "Zor", lvl: "A1", cat: "Sıfat" },
  { en: "dinner", tr: "Akşam Yemeği", lvl: "A1", cat: "Yemek" },
  { en: "direction", tr: "Yön / Talimat", lvl: "A2", cat: "Yer" },
  { en: "director", tr: "Müdür / Yönetmen", lvl: "A2", cat: "Meslek" },
  { en: "dirty", tr: "Kirli", lvl: "A1", cat: "Sıfat" },
  { en: "disease", tr: "Hastalık", lvl: "A2", cat: "Sağlık" },
  { en: "divided", tr: "Bölünmüş", lvl: "B1", cat: "Sıfat" },
  { en: "do", tr: "Yapmak", lvl: "A1", cat: "Fiil" },
  { en: "doctor", tr: "Doktor", lvl: "A1", cat: "Meslek" },
  { en: "dog", tr: "Köpek", lvl: "A1", cat: "Hayvan" },
  { en: "dollar", tr: "Dolar", lvl: "A1", cat: "Para" },
  { en: "donkey", tr: "Eşek", lvl: "A1", cat: "Hayvan" },
  { en: "door", tr: "Kapı", lvl: "A1", cat: "Eşya" },
  { en: "double", tr: "Çift / İki Kat", lvl: "A1", cat: "Sıfat" },
  { en: "down", tr: "Aşağı", lvl: "A1", cat: "Zarf" },
  { en: "draw", tr: "Çizmek", lvl: "A1", cat: "Fiil" },
  { en: "drink", tr: "İçmek", lvl: "A1", cat: "Fiil" },
  { en: "drive", tr: "Sürmek", lvl: "A1", cat: "Fiil" },
  { en: "driver", tr: "Sürücü", lvl: "A1", cat: "Meslek" },
  { en: "during", tr: "Sırasında", lvl: "A2", cat: "Edat" },
  { en: "duty", tr: "Görev", lvl: "A2", cat: "İsim" },

  // E
  { en: "each", tr: "her biri", lvl: "A1", cat: "Belirteç" },
{ en: "ear", tr: "kulak", lvl: "A1", cat: "Vücut" },
{ en: "early", tr: "erken", lvl: "A1", cat: "Zaman" },
{ en: "earring", tr: "küpe", lvl: "A1", cat: "Aksesuar" },
{ en: "easily", tr: "kolayca", lvl: "A2", cat: "Zarf" },
{ en: "easy", tr: "kolay", lvl: "A1", cat: "Sıfat" },
{ en: "eat", tr: "yemek yemek", lvl: "A1", cat: "Fiil" },
{ en: "education", tr: "eğitim", lvl: "A2", cat: "Soyut Kavram" },
{ en: "egg", tr: "yumurta", lvl: "A1", cat: "Yiyecek" },
{ en: "else", tr: "başka", lvl: "A1", cat: "Belirteç" },
{ en: "e-mail", tr: "e-posta", lvl: "A2", cat: "İletişim" },
{ en: "employer", tr: "işveren", lvl: "B1", cat: "İş Hayatı" },
{ en: "empty", tr: "boş", lvl: "A1", cat: "Sıfat" },
{ en: "end", tr: "son", lvl: "A1", cat: "Zaman" },
{ en: "energy", tr: "enerji", lvl: "A2", cat: "Soyut Kavram" },
{ en: "engine", tr: "motor", lvl: "B1", cat: "Teknoloji" },
{ en: "english", tr: "İngilizce", lvl: "A1", cat: "Dil" },
{ en: "enjoy", tr: "keyif almak", lvl: "A1", cat: "Fiil" },
{ en: "enough", tr: "yeterli", lvl: "A1", cat: "Belirteç" },
{ en: "enter", tr: "girmek", lvl: "A1", cat: "Fiil" },
{ en: "equal", tr: "eşit", lvl: "A2", cat: "Sıfat" },
{ en: "especially", tr: "özellikle", lvl: "A2", cat: "Zarf" },
{ en: "evening", tr: "akşam", lvl: "A1", cat: "Zaman" },
{ en: "every", tr: "her", lvl: "A1", cat: "Belirteç" },
{ en: "everybody", tr: "herkes", lvl: "A1", cat: "Zamir" },
{ en: "everyone", tr: "herkes", lvl: "A1", cat: "Zamir" },
{ en: "everything", tr: "her şey", lvl: "A1", cat: "Zamir" },
{ en: "everywhere", tr: "her yerde", lvl: "A1", cat: "Zarf" },
{ en: "exam", tr: "sınav", lvl: "A1", cat: "Eğitim" },
{ en: "example", tr: "örnek", lvl: "A1", cat: "Eğitim" },
{ en: "exercise", tr: "egzersiz", lvl: "A1", cat: "Sağlık" },
{ en: "explain", tr: "açıklamak", lvl: "A2", cat: "Fiil" },
{ en: "extra", tr: "ekstra", lvl: "A1", cat: "Sıfat" },
{ en: "eye", tr: "göz", lvl: "A1", cat: "Vücut" },
{ en: "eyebrow", tr: "kaş", lvl: "A1", cat: "Vücut" },
{ en: "eyelash", tr: "kirpik", lvl: "A1", cat: "Vücut" },
{ en: "eyelid", tr: "göz kapağı", lvl: "A1", cat: "Vücut" },

// F
{ en: "face", tr: "yüz", lvl: "A1", cat: "Vücut" },
{ en: "fact", tr: "gerçek", lvl: "A2", cat: "Soyut Kavram" },
{ en: "fall", tr: "düşmek", lvl: "A1", cat: "Fiil" },
{ en: "family", tr: "aile", lvl: "A1", cat: "İnsanlar" },
{ en: "far", tr: "uzak", lvl: "A1", cat: "Sıfat" },
{ en: "father", tr: "baba", lvl: "A1", cat: "İnsanlar" },
{ en: "father-in-law", tr: "kayınpeder", lvl: "A1", cat: "İnsanlar" },
{ en: "fault", tr: "hata", lvl: "A2", cat: "Soyut Kavram" },
{ en: "february", tr: "şubat", lvl: "A1", cat: "Zaman" },
{ en: "feed", tr: "beslemek", lvl: "A2", cat: "Fiil" },
{ en: "feel", tr: "hissetmek", lvl: "A1", cat: "Fiil" },
{ en: "feeling", tr: "his, duygu", lvl: "A1", cat: "Soyut Kavram" },
{ en: "feet", tr: "ayaklar", lvl: "A1", cat: "Vücut" },
{ en: "ferry", tr: "feribot", lvl: "A1", cat: "Ulaşım" },
{ en: "few", tr: "az (sayılabilir)", lvl: "A1", cat: "Miktar" },
{ en: "a few", tr: "birkaç", lvl: "A1", cat: "Miktar" },
{ en: "field", tr: "tarla, alan", lvl: "A2", cat: "Yer" },
{ en: "fig", tr: "incir", lvl: "A1", cat: "Meyve" },
{ en: "fight", tr: "kavga etmek", lvl: "A2", cat: "Fiil" },
{ en: "fought", tr: "savaştı (fight geçmiş)", lvl: "A2", cat: "Fiil" },
{ en: "fill", tr: "doldurmak", lvl: "A1", cat: "Fiil" },
{ en: "film", tr: "film", lvl: "A1", cat: "Sanat" },
{ en: "final", tr: "son, final", lvl: "A2", cat: "Sıfat" },
{ en: "find", tr: "bulmak", lvl: "A1", cat: "Fiil" },
{ en: "fine", tr: "iyi, güzel", lvl: "A1", cat: "Sıfat" },
{ en: "finger", tr: "parmak", lvl: "A1", cat: "Vücut" },
{ en: "finish", tr: "bitirmek", lvl: "A1", cat: "Fiil" },
{ en: "fire", tr: "ateş", lvl: "A1", cat: "Doğa" },
{ en: "firm", tr: "firma", lvl: "B1", cat: "İş Hayatı" },
{ en: "first", tr: "ilk", lvl: "A1", cat: "Sayı / Sıra" },
{ en: "fish", tr: "balık", lvl: "A1", cat: "Hayvan" },
{ en: "flag", tr: "bayrak", lvl: "A1", cat: "Nesne" },
{ en: "floor", tr: "zemin, kat", lvl: "A1", cat: "Yer" },
{ en: "flower", tr: "çiçek", lvl: "A1", cat: "Bitki" },
{ en: "follow", tr: "takip etmek", lvl: "A1", cat: "Fiil" },
{ en: "food", tr: "yiyecek", lvl: "A1", cat: "Yiyecek" },
{ en: "foot", tr: "ayak", lvl: "A1", cat: "Vücut" },
{ en: "football", tr: "futbol", lvl: "A1", cat: "Spor" },
{ en: "for", tr: "için", lvl: "A1", cat: "Edat" },
{ en: "forget", tr: "unutmak", lvl: "A1", cat: "Fiil" },
{ en: "fork", tr: "çatal", lvl: "A1", cat: "Mutfak" },
{ en: "form", tr: "form, biçim", lvl: "A2", cat: "Soyut Kavram" },
{ en: "forward", tr: "ileri", lvl: "A2", cat: "Yön" },
{ en: "free", tr: "özgür, bedava", lvl: "A1", cat: "Sıfat" },
{ en: "friday", tr: "cuma", lvl: "A1", cat: "Zaman" },
{ en: "friend", tr: "arkadaş", lvl: "A1", cat: "İnsanlar" },
{ en: "from", tr: "-den, -dan", lvl: "A1", cat: "Edat" },
{ en: "front", tr: "ön", lvl: "A1", cat: "Konum" },
{ en: "in front of", tr: "önünde", lvl: "A1", cat: "Konum" },
{ en: "full", tr: "dolu", lvl: "A1", cat: "Sıfat" },
{ en: "fun", tr: "eğlence", lvl: "A1", cat: "Soyut Kavram" },
{ en: "funny", tr: "komik", lvl: "A1", cat: "Sıfat" },
{ en: "future", tr: "gelecek", lvl: "A2", cat: "Zaman" },

// G
{ en: "game", tr: "oyun", lvl: "A1", cat: "Eğlence" },
{ en: "garden", tr: "bahçe", lvl: "A1", cat: "Yer" },
{ en: "garlic", tr: "sarımsak", lvl: "A1", cat: "Yiyecek" },
{ en: "gas", tr: "gaz", lvl: "A2", cat: "Madde" },
{ en: "gasoline", tr: "benzin", lvl: "A2", cat: "Yakıt" },
{ en: "general", tr: "genel", lvl: "A2", cat: "Sıfat" },
{ en: "generally", tr: "genellikle", lvl: "A2", cat: "Zarf" },
{ en: "get", tr: "almak, elde etmek", lvl: "A1", cat: "Fiil" },
{ en: "giant", tr: "dev", lvl: "A2", cat: "Sıfat" },
{ en: "gift", tr: "hediye", lvl: "A1", cat: "Nesne" },
{ en: "girl", tr: "kız", lvl: "A1", cat: "İnsanlar" },
{ en: "give", tr: "vermek", lvl: "A1", cat: "Fiil" },
{ en: "glass", tr: "bardak / cam", lvl: "A1", cat: "Nesne" },
{ en: "glasses", tr: "gözlük", lvl: "A1", cat: "Aksesuar" },
{ en: "glove", tr: "eldiven", lvl: "A1", cat: "Giyim" },
{ en: "go", tr: "gitmek", lvl: "A1", cat: "Fiil" },
{ en: "goal", tr: "gol, hedef", lvl: "A1", cat: "Spor" },
{ en: "goalkeeper", tr: "kaleci", lvl: "A1", cat: "Spor" },
{ en: "good", tr: "iyi", lvl: "A1", cat: "Sıfat" },
{ en: "goodbye", tr: "hoşça kal", lvl: "A1", cat: "İfade" },
{ en: "government", tr: "hükümet", lvl: "B1", cat: "Siyaset" },
{ en: "grape", tr: "üzüm", lvl: "A1", cat: "Meyve" },
{ en: "grapefruit", tr: "greyfurt", lvl: "A1", cat: "Meyve" },
{ en: "great", tr: "harika, büyük", lvl: "A1", cat: "Sıfat" },
{ en: "green", tr: "yeşil", lvl: "A1", cat: "Renk" },
{ en: "greengrocer", tr: "manav", lvl: "A1", cat: "Meslek" },
{ en: "greeting", tr: "selamlama", lvl: "A2", cat: "İletişim" },
{ en: "group", tr: "grup", lvl: "A1", cat: "İnsanlar" },
{ en: "grow", tr: "büyümek, yetişmek", lvl: "A1", cat: "Fiil" },

// H
{ en: "hair", tr: "saç", lvl: "A1", cat: "Vücut" },
{ en: "hairdresser", tr: "kuaför", lvl: "A1", cat: "Meslek" },
{ en: "half", tr: "yarım", lvl: "A1", cat: "Miktar" },
{ en: "hall", tr: "hol, salon", lvl: "A1", cat: "Yer" },
{ en: "hallo", tr: "merhaba", lvl: "A1", cat: "İfade" },
{ en: "hamburger", tr: "hamburger", lvl: "A1", cat: "Yiyecek" },
{ en: "hand", tr: "el", lvl: "A1", cat: "Vücut" },
{ en: "handkerchief", tr: "mendil", lvl: "A1", cat: "Eşya" },
{ en: "handsome", tr: "yakışıklı", lvl: "A1", cat: "Sıfat" },
{ en: "happiness", tr: "mutluluk", lvl: "A2", cat: "Soyut Kavram" },
{ en: "happy", tr: "mutlu", lvl: "A1", cat: "Sıfat" },
{ en: "hard", tr: "zor, sert", lvl: "A1", cat: "Sıfat" },
{ en: "hat", tr: "şapka", lvl: "A1", cat: "Giyim" },
{ en: "has", tr: "sahip (have 3. tekil)", lvl: "A1", cat: "Fiil" },
{ en: "have", tr: "sahip olmak", lvl: "A1", cat: "Fiil" },
{ en: "have got", tr: "sahip olmak", lvl: "A1", cat: "Fiil" },
{ en: "hazelnut", tr: "fındık", lvl: "A1", cat: "Kuruyemiş" },
{ en: "he", tr: "o (erkek)", lvl: "A1", cat: "Zamir" },
{ en: "head", tr: "kafa", lvl: "A1", cat: "Vücut" },
{ en: "hear", tr: "duymak", lvl: "A1", cat: "Fiil" },
{ en: "heart", tr: "kalp", lvl: "A1", cat: "Vücut" },
{ en: "heavy", tr: "ağır", lvl: "A1", cat: "Sıfat" },
{ en: "hello", tr: "merhaba", lvl: "A1", cat: "İfade" },
{ en: "help", tr: "yardım etmek", lvl: "A1", cat: "Fiil" },
{ en: "hen", tr: "tavuk (dişi)", lvl: "A1", cat: "Hayvan" },
{ en: "her", tr: "onun (kadın)", lvl: "A1", cat: "Zamir" },
{ en: "here", tr: "burada", lvl: "A1", cat: "Yer" },
{ en: "herself", tr: "kendi (kadın)", lvl: "A1", cat: "Zamir" },
{ en: "hi", tr: "selam", lvl: "A1", cat: "İfade" },
{ en: "high", tr: "yüksek", lvl: "A1", cat: "Sıfat" },
{ en: "him", tr: "onu / ona", lvl: "A1", cat: "Zamir" },
{ en: "himself", tr: "kendi (erkek)", lvl: "A1", cat: "Zamir" },
{ en: "hire", tr: "kiralamak", lvl: "A2", cat: "Fiil" },
{ en: "his", tr: "onun (erkek)", lvl: "A1", cat: "Zamir" },
{ en: "hit", tr: "vurmak", lvl: "A1", cat: "Fiil" },
{ en: "hold", tr: "tutmak", lvl: "A1", cat: "Fiil" },
{ en: "hole", tr: "delik", lvl: "A1", cat: "Nesne" },
{ en: "home", tr: "ev", lvl: "A1", cat: "Yer" },
{ en: "homework", tr: "ödev", lvl: "A1", cat: "Eğitim" },
{ en: "honest", tr: "dürüst", lvl: "A2", cat: "Sıfat" },
{ en: "hope", tr: "umut etmek", lvl: "A1", cat: "Fiil" },
{ en: "hopeful", tr: "umutlu", lvl: "A2", cat: "Sıfat" },
{ en: "horse", tr: "at", lvl: "A1", cat: "Hayvan" },
{ en: "hospital", tr: "hastane", lvl: "A1", cat: "Yer" },
{ en: "hot", tr: "sıcak", lvl: "A1", cat: "Sıfat" },
{ en: "hotel", tr: "otel", lvl: "A1", cat: "Yer" },
{ en: "hour", tr: "saat", lvl: "A1", cat: "Zaman" },
{ en: "house", tr: "ev", lvl: "A1", cat: "Yer" },
{ en: "how", tr: "nasıl", lvl: "A1", cat: "Soru" },
{ en: "how many", tr: "kaç tane", lvl: "A1", cat: "Soru" },
{ en: "how much", tr: "ne kadar", lvl: "A1", cat: "Soru" },
{ en: "hungry", tr: "aç", lvl: "A1", cat: "Durum" },
{ en: "husband", tr: "koca", lvl: "A1", cat: "İnsanlar" },
{ en: "hut", tr: "kulübe", lvl: "A1", cat: "Yer" },

// I
{ en: "I", tr: "ben", lvl: "A1", cat: "Zamir" },
{ en: "idea", tr: "fikir", lvl: "A1", cat: "Soyut Kavram" },
{ en: "if", tr: "eğer", lvl: "A1", cat: "Bağlaç" },
{ en: "important", tr: "önemli", lvl: "A1", cat: "Sıfat" },
{ en: "in", tr: "içinde", lvl: "A1", cat: "Edat" },
{ en: "income", tr: "gelir", lvl: "A2", cat: "Ekonomi" },
{ en: "information", tr: "bilgi", lvl: "A1", cat: "Soyut Kavram" },
{ en: "ink", tr: "mürekkep", lvl: "A1", cat: "Nesne" },
{ en: "interesting", tr: "ilginç", lvl: "A1", cat: "Sıfat" },
{ en: "international", tr: "uluslararası", lvl: "A2", cat: "Sıfat" },
{ en: "internet", tr: "internet", lvl: "A1", cat: "Teknoloji" },
{ en: "into", tr: "içine", lvl: "A1", cat: "Edat" },
{ en: "irregular", tr: "düzensiz / kuralsız", lvl: "A2", cat: "Sıfat" },
{ en: "it", tr: "o (cansız)", lvl: "A1", cat: "Zamir" },
{ en: "its", tr: "onun (cansız)", lvl: "A1", cat: "Zamir" },
{ en: "itself", tr: "kendi", lvl: "A1", cat: "Zamir" },

// J
{ en: "jacket", tr: "ceket", lvl: "A1", cat: "Giyim" },
{ en: "jam", tr: "reçel", lvl: "A1", cat: "Yiyecek" },
{ en: "january", tr: "ocak", lvl: "A1", cat: "Zaman" },
{ en: "jaw", tr: "çene", lvl: "A2", cat: "Vücut" },
{ en: "job", tr: "iş", lvl: "A1", cat: "Meslek" },
{ en: "join", tr: "katılmak", lvl: "A1", cat: "Fiil" },
{ en: "joy", tr: "sevinç", lvl: "A2", cat: "Duygu" },
{ en: "juice", tr: "meyve suyu", lvl: "A1", cat: "İçecek" },
{ en: "july", tr: "temmuz", lvl: "A1", cat: "Zaman" },
{ en: "june", tr: "haziran", lvl: "A1", cat: "Zaman" },
{ en: "just", tr: "sadece / az önce", lvl: "A1", cat: "Zarf" },

// K
{ en: "keep", tr: "tutmak / saklamak", lvl: "A1", cat: "Fiil" },
{ en: "kettle", tr: "su ısıtıcısı", lvl: "A1", cat: "Ev Eşyası" },
{ en: "key", tr: "anahtar", lvl: "A1", cat: "Eşya" },
{ en: "kill", tr: "öldürmek", lvl: "A2", cat: "Fiil" },
{ en: "kilo", tr: "kilo", lvl: "A1", cat: "Ölçü" },
{ en: "kilogram", tr: "kilogram", lvl: "A1", cat: "Ölçü" },
{ en: "kilometre", tr: "kilometre", lvl: "A1", cat: "Ölçü" },
{ en: "kind", tr: "nazik / tür", lvl: "A1", cat: "Sıfat" },
{ en: "king", tr: "kral", lvl: "A1", cat: "İnsan" },
{ en: "kiss", tr: "öpücük / öpmek", lvl: "A1", cat: "Fiil" },
{ en: "kitchen", tr: "mutfak", lvl: "A1", cat: "Yer" },
{ en: "kite", tr: "uçurtma", lvl: "A1", cat: "Oyuncak" },
{ en: "know", tr: "bilmek", lvl: "A1", cat: "Fiil" },

// L
{ en: "land", tr: "arazi / kara", lvl: "A2", cat: "Yer" },
{ en: "language", tr: "dil", lvl: "A1", cat: "İletişim" },
{ en: "large", tr: "büyük", lvl: "A1", cat: "Sıfat" },
{ en: "last", tr: "son", lvl: "A1", cat: "Zaman" },
{ en: "late", tr: "geç", lvl: "A1", cat: "Zaman" },
{ en: "later", tr: "sonra", lvl: "A1", cat: "Zaman" },
{ en: "law", tr: "kanun", lvl: "A2", cat: "Toplum" },
{ en: "lazy", tr: "tembel", lvl: "A1", cat: "Sıfat" },
{ en: "learn", tr: "öğrenmek", lvl: "A1", cat: "Fiil" },
{ en: "left", tr: "sol", lvl: "A1", cat: "Yön" },
{ en: "leg", tr: "bacak", lvl: "A1", cat: "Vücut" },
{ en: "lemon", tr: "limon", lvl: "A1", cat: "Meyve" },
{ en: "less", tr: "daha az", lvl: "A1", cat: "Miktar" },
{ en: "lesson", tr: "ders", lvl: "A1", cat: "Eğitim" },
{ en: "let", tr: "izin vermek", lvl: "A1", cat: "Fiil" },
{ en: "let's", tr: "hadi", lvl: "A1", cat: "İfade" },
{ en: "letter", tr: "mektup / harf", lvl: "A1", cat: "İletişim" },
{ en: "library", tr: "kütüphane", lvl: "A1", cat: "Yer" },
{ en: "lid", tr: "kapak", lvl: "A2", cat: "Eşya" },
{ en: "life", tr: "hayat", lvl: "A1", cat: "Soyut Kavram" },
{ en: "light", tr: "ışık / hafif", lvl: "A1", cat: "Sıfat" },
{ en: "like", tr: "sevmek / gibi", lvl: "A1", cat: "Fiil" },
{ en: "line", tr: "çizgi / sıra", lvl: "A1", cat: "Nesne" },
{ en: "list", tr: "liste", lvl: "A1", cat: "Nesne" },
{ en: "listen", tr: "dinlemek", lvl: "A1", cat: "Fiil" },
{ en: "litre", tr: "litre", lvl: "A1", cat: "Ölçü" },
{ en: "little", tr: "küçük / az", lvl: "A1", cat: "Miktar" },
{ en: "a little", tr: "biraz", lvl: "A1", cat: "Miktar" },
{ en: "live", tr: "yaşamak", lvl: "A1", cat: "Fiil" },
{ en: "loaf", tr: "ekmek somunu", lvl: "A1", cat: "Yiyecek" },
{ en: "local", tr: "yerel", lvl: "A1", cat: "Sıfat" },
{ en: "lock", tr: "kilitlemek / kilit", lvl: "A1", cat: "Fiil" },
{ en: "long", tr: "uzun", lvl: "A1", cat: "Sıfat" },
{ en: "look", tr: "bakmak", lvl: "A1", cat: "Fiil" },
{ en: "lose", tr: "kaybetmek", lvl: "A1", cat: "Fiil" },
{ en: "loss", tr: "kayıp", lvl: "A2", cat: "Soyut Kavram" },
{ en: "lot", tr: "çok (a lot)", lvl: "A1", cat: "Miktar" },
{ en: "love", tr: "sevmek / aşk", lvl: "A1", cat: "Duygu" },
{ en: "low", tr: "alçak / düşük", lvl: "A1", cat: "Sıfat" },
{ en: "luck", tr: "şans", lvl: "A1", cat: "Soyut Kavram" },
{ en: "luggage", tr: "bagaj", lvl: "A1", cat: "Eşya" },
{ en: "lunch", tr: "öğle yemeği", lvl: "A1", cat: "Yemek" },
{ en: "lung", tr: "akciğer", lvl: "A2", cat: "Vücut" },

// M
{ en: "machine", tr: "makine", lvl: "A1", cat: "Nesne" },
{ en: "mad", tr: "deli / kızgın", lvl: "A1", cat: "Sıfat" },
{ en: "madam", tr: "hanımefendi", lvl: "A1", cat: "İnsan" },
{ en: "main", tr: "ana / temel", lvl: "A1", cat: "Sıfat" },
{ en: "make", tr: "yapmak", lvl: "A1", cat: "Fiil" },
{ en: "man", tr: "adam", lvl: "A1", cat: "İnsan" },
{ en: "manager", tr: "yönetici", lvl: "A1", cat: "Meslek" },
{ en: "many", tr: "çok (sayılabilen)", lvl: "A1", cat: "Miktar" },
{ en: "march", tr: "mart", lvl: "A1", cat: "Zaman" },
{ en: "market", tr: "pazar / market", lvl: "A1", cat: "Yer" },
{ en: "marry", tr: "evlenmek", lvl: "A1", cat: "Fiil" },
{ en: "material", tr: "malzeme", lvl: "A2", cat: "Nesne" },
{ en: "maximum", tr: "maksimum", lvl: "A2", cat: "Miktar" },
{ en: "may", tr: "mayıs / -ebilir", lvl: "A1", cat: "Zaman" },
{ en: "maybe", tr: "belki", lvl: "A1", cat: "Zarf" },
{ en: "me", tr: "beni / bana", lvl: "A1", cat: "Zamir" },
{ en: "meaning", tr: "anlam", lvl: "A1", cat: "Soyut Kavram" },
{ en: "mechanic", tr: "tamirci", lvl: "A1", cat: "Meslek" },
{ en: "meet", tr: "buluşmak", lvl: "A1", cat: "Fiil" },
{ en: "met", tr: "buluştu (meet)", lvl: "A1", cat: "Fiil" },
{ en: "meeting", tr: "toplantı", lvl: "A1", cat: "İş" },
{ en: "melon", tr: "kavun", lvl: "A1", cat: "Meyve" },
{ en: "member", tr: "üye", lvl: "A1", cat: "İnsan" },
{ en: "memory", tr: "hafıza / anı", lvl: "A2", cat: "Soyut Kavram" },
{ en: "message", tr: "mesaj", lvl: "A1", cat: "İletişim" },
{ en: "method", tr: "yöntem", lvl: "A2", cat: "Soyut Kavram" },
{ en: "middle", tr: "orta", lvl: "A1", cat: "Konum" },
{ en: "in the middle of", tr: "ortasında", lvl: "A1", cat: "Edat" },
{ en: "mile", tr: "mil", lvl: "A1", cat: "Ölçü" },
{ en: "military", tr: "askeri", lvl: "A2", cat: "Toplum" },
{ en: "milk", tr: "süt", lvl: "A1", cat: "İçecek" },
{ en: "mind", tr: "zihin", lvl: "A2", cat: "Soyut Kavram" },
{ en: "mine", tr: "benimki", lvl: "A1", cat: "Zamir" },
{ en: "minimum", tr: "minimum", lvl: "A2", cat: "Miktar" },
{ en: "minus", tr: "eksi", lvl: "A1", cat: "Matematik" },
{ en: "minute", tr: "dakika", lvl: "A1", cat: "Zaman" },
{ en: "miss", tr: "kaçırmak / bayan", lvl: "A1", cat: "Fiil" },
{ en: "mising", tr: "eksik (missing)", lvl: "A1", cat: "Sıfat" },
{ en: "mistake", tr: "hata", lvl: "A1", cat: "Soyut Kavram" },
{ en: "mixture", tr: "karışım", lvl: "A2", cat: "Nesne" },
{ en: "modern", tr: "modern", lvl: "A1", cat: "Sıfat" },
{ en: "moment", tr: "an", lvl: "A1", cat: "Zaman" },
{ en: "monday", tr: "pazartesi", lvl: "A1", cat: "Zaman" },
{ en: "money", tr: "para", lvl: "A1", cat: "Ekonomi" },
{ en: "month", tr: "ay", lvl: "A1", cat: "Zaman" },
{ en: "more", tr: "daha fazla", lvl: "A1", cat: "Miktar" },
{ en: "morning", tr: "sabah", lvl: "A1", cat: "Zaman" },
{ en: "mosque", tr: "cami", lvl: "A1", cat: "Yer" },
{ en: "most", tr: "en çok", lvl: "A1", cat: "Miktar" },
{ en: "mother", tr: "anne", lvl: "A1", cat: "İnsan" },
{ en: "mother-in-law", tr: "kaynana", lvl: "A1", cat: "İnsan" },
{ en: "mountain", tr: "dağ", lvl: "A1", cat: "Doğa" },
{ en: "mouse", tr: "fare", lvl: "A1", cat: "Hayvan" },
{ en: "mouth", tr: "ağız", lvl: "A1", cat: "Vücut" },
{ en: "move", tr: "hareket etmek", lvl: "A1", cat: "Fiil" },
{ en: "movie", tr: "film", lvl: "A1", cat: "Eğlence" },
{ en: "mr", tr: "bay", lvl: "A1", cat: "Unvan" },
{ en: "mrs", tr: "bayan", lvl: "A1", cat: "Unvan" },
{ en: "much", tr: "çok (sayılamayan)", lvl: "A1", cat: "Miktar" },
{ en: "mummy", tr: "anne (çocuk dili)", lvl: "A1", cat: "İnsan" },
{ en: "music", tr: "müzik", lvl: "A1", cat: "Sanat" },
{ en: "musician", tr: "müzisyen", lvl: "A1", cat: "Meslek" },
{ en: "must", tr: "zorunda olmak", lvl: "A1", cat: "Modal" },
{ en: "my", tr: "benim", lvl: "A1", cat: "Zamir" },
{ en: "myself", tr: "kendim", lvl: "A1", cat: "Zamir" },

// N
{ en: "name", tr: "isim", lvl: "A1", cat: "Soyut Kavram" },
{ en: "national", tr: "ulusal", lvl: "A2", cat: "Sıfat" },
{ en: "nature", tr: "doğa", lvl: "A1", cat: "Doğa" },
{ en: "near", tr: "yakın", lvl: "A1", cat: "Zarf / Edat" },
{ en: "necessary", tr: "gerekli", lvl: "A2", cat: "Sıfat" },
{ en: "need", tr: "ihtiyaç duymak / gerekmek", lvl: "A1", cat: "Fiil" },
{ en: "never", tr: "hiçbir zaman", lvl: "A1", cat: "Zarf" },
{ en: "new", tr: "yeni", lvl: "A1", cat: "Sıfat" },
{ en: "news", tr: "haber", lvl: "A1", cat: "İletişim" },
{ en: "newspaper", tr: "gazete", lvl: "A1", cat: "İletişim" },
{ en: "next", tr: "sonraki", lvl: "A1", cat: "Sıfat / Zarf" },
{ en: "nice", tr: "güzel / hoş", lvl: "A1", cat: "Sıfat" },
{ en: "night", tr: "gece", lvl: "A1", cat: "Zaman" },
{ en: "no", tr: "hayır", lvl: "A1", cat: "Zarf" },
{ en: "no one", tr: "hiç kimse", lvl: "A1", cat: "Zamir" },
{ en: "nobody", tr: "hiç kimse", lvl: "A1", cat: "Zamir" },
{ en: "none", tr: "hiçbiri", lvl: "A1", cat: "Zamir" },
{ en: "noon", tr: "öğle", lvl: "A1", cat: "Zaman" },
{ en: "normal", tr: "normal", lvl: "A1", cat: "Sıfat" },
{ en: "normally", tr: "normalde", lvl: "A1", cat: "Zarf" },
{ en: "north", tr: "kuzey", lvl: "A1", cat: "Yön" },
{ en: "not", tr: "değil", lvl: "A1", cat: "Zarf" },
{ en: "note", tr: "not", lvl: "A1", cat: "Nesne" },
{ en: "notebook", tr: "defter", lvl: "A1", cat: "Nesne" },
{ en: "nothing", tr: "hiçbir şey", lvl: "A1", cat: "Zamir" },
{ en: "noun", tr: "isim (gramer)", lvl: "A2", cat: "Dilbilgisi" },
{ en: "november", tr: "kasım", lvl: "A1", cat: "Zaman" },
{ en: "now", tr: "şimdi", lvl: "A1", cat: "Zaman / Zarf" },
{ en: "number", tr: "sayı", lvl: "A1", cat: "Sayı / Soyut Kavram" },
{ en: "nurse", tr: "hemşire", lvl: "A1", cat: "Meslek" },
{ en: "nut", tr: "fındık / kuruyemiş", lvl: "A1", cat: "Yiyecek" },

// O
{ en: "ocean", tr: "okyanus", lvl: "A2", cat: "Doğa" },
{ en: "o'clock", tr: "saat …", lvl: "A1", cat: "Zaman" },
{ en: "october", tr: "ekim", lvl: "A1", cat: "Zaman" },
{ en: "of", tr: "…nın / …nin", lvl: "A1", cat: "Edat" },
{ en: "of course", tr: "elbette", lvl: "A1", cat: "Zarf" },
{ en: "off", tr: "kapalı / dışında", lvl: "A1", cat: "Zarf / Edat" },
{ en: "office", tr: "ofis", lvl: "A1", cat: "Yer" },
{ en: "officer", tr: "memur", lvl: "A2", cat: "Meslek" },
{ en: "often", tr: "sık sık", lvl: "A1", cat: "Zarf" },
{ en: "OK", tr: "tamam", lvl: "A1", cat: "Zarf" },
{ en: "okay", tr: "tamam", lvl: "A1", cat: "Zarf" },
{ en: "old", tr: "yaşlı / eski", lvl: "A1", cat: "Sıfat" },
{ en: "olive", tr: "zeytin", lvl: "A1", cat: "Yiyecek" },
{ en: "on", tr: "üzerinde / açık", lvl: "A1", cat: "Edat" },
{ en: "once", tr: "bir kez", lvl: "A1", cat: "Zarf" },
{ en: "one", tr: "bir", lvl: "A1", cat: "Sayı / Zamir" },
{ en: "only", tr: "sadece", lvl: "A1", cat: "Zarf" },
{ en: "open", tr: "açmak / açık", lvl: "A1", cat: "Fiil / Sıfat" },
{ en: "or", tr: "veya", lvl: "A1", cat: "Bağlaç" },
{ en: "orange", tr: "portakal", lvl: "A1", cat: "Yiyecek / Renk" },
{ en: "order", tr: "sipariş / düzenlemek", lvl: "A2", cat: "İsim / Fiil" },
{ en: "organize", tr: "düzenlemek", lvl: "A2", cat: "Fiil" },
{ en: "original", tr: "orijinal", lvl: "A2", cat: "Sıfat" },
{ en: "other", tr: "diğer", lvl: "A1", cat: "Sıfat / Zamir" },
{ en: "our", tr: "bizim", lvl: "A1", cat: "Zamir" },
{ en: "ours", tr: "bizimki", lvl: "A1", cat: "Zamir" },
{ en: "ourselves", tr: "kendimiz", lvl: "A1", cat: "Zamir" },
{ en: "out", tr: "dışarı / kapalı", lvl: "A1", cat: "Zarf / Edat" },
{ en: "outside", tr: "dışarıda / dışında", lvl: "A1", cat: "Zarf / Edat" },
{ en: "over", tr: "üzerinde / bitmiş", lvl: "A1", cat: "Edat / Zarf" },
{ en: "own", tr: "sahip olmak / kendi", lvl: "A2", cat: "Fiil / Sıfat" },

// P
{ en: "p.m.", tr: "öğleden sonra", lvl: "A1", cat: "Zaman" },
{ en: "page", tr: "sayfa", lvl: "A1", cat: "Nesne" },
{ en: "painter", tr: "ressam", lvl: "A2", cat: "Meslek" },
{ en: "paper", tr: "kağıt", lvl: "A1", cat: "Nesne" },
{ en: "parents", tr: "ebeveynler", lvl: "A1", cat: "İnsan" },
{ en: "park", tr: "park", lvl: "A1", cat: "Yer" },
{ en: "part", tr: "parça / bölüm", lvl: "A1", cat: "Soyut Kavram" },
{ en: "party", tr: "parti / kutlama", lvl: "A1", cat: "Etkinlik" },
{ en: "pass", tr: "geçmek", lvl: "A1", cat: "Fiil" },
{ en: "path", tr: "yol / patika", lvl: "A1", cat: "Yer" },
{ en: "pay", tr: "ödemek", lvl: "A1", cat: "Fiil" },
{ en: "pen", tr: "kalem", lvl: "A1", cat: "Nesne" },
{ en: "pencil", tr: "kurşun kalem", lvl: "A1", cat: "Nesne" },
{ en: "people", tr: "insanlar", lvl: "A1", cat: "İnsan" },
{ en: "perhaps", tr: "belki", lvl: "A2", cat: "Zarf" },
{ en: "person", tr: "kişi", lvl: "A1", cat: "İnsan" },
{ en: "pharmacy", tr: "eczane", lvl: "A2", cat: "Yer" },
{ en: "phone", tr: "telefon", lvl: "A1", cat: "Nesne" },
{ en: "phonecard", tr: "telefon kartı", lvl: "A2", cat: "Nesne" },
{ en: "piano", tr: "piyano", lvl: "A1", cat: "Müzik" },
{ en: "pick", tr: "almak / seçmek", lvl: "A2", cat: "Fiil" },
{ en: "picnic", tr: "piknik", lvl: "A1", cat: "Etkinlik" },
{ en: "picture", tr: "resim / fotoğraf", lvl: "A1", cat: "Nesne" },
{ en: "piece", tr: "parça", lvl: "A1", cat: "Nesne" },
{ en: "pig", tr: "domuz", lvl: "A1", cat: "Hayvan" },
{ en: "ping-pong", tr: "masa tenisi", lvl: "A2", cat: "Spor" },
{ en: "place", tr: "yer", lvl: "A1", cat: "Yer" },
{ en: "plan", tr: "plan / planlamak", lvl: "A1", cat: "Soyut Kavram / Fiil" },
{ en: "play", tr: "oynamak / oyun", lvl: "A1", cat: "Fiil / Etkinlik" },
{ en: "player", tr: "oyuncu", lvl: "A1", cat: "İnsan" },
{ en: "please", tr: "lütfen", lvl: "A1", cat: "Zarf" },
{ en: "pleased", tr: "memnun", lvl: "A2", cat: "Duygu" },
{ en: "plural", tr: "çoğul", lvl: "A2", cat: "Dilbilgisi" },
{ en: "point", tr: "nokta / puan", lvl: "A1", cat: "Soyut Kavram / Nesne" },
{ en: "police", tr: "polis", lvl: "A1", cat: "Meslek" },
{ en: "policeman", tr: "polis", lvl: "A1", cat: "Meslek" },
{ en: "policewoman", tr: "kadın polis", lvl: "A1", cat: "Meslek" },
{ en: "pool", tr: "havuz", lvl: "A1", cat: "Yer" },
{ en: "poor", tr: "fakir / kötü", lvl: "A1", cat: "Sıfat" },
{ en: "popcorn", tr: "patlamış mısır", lvl: "A1", cat: "Yiyecek" },
{ en: "pork", tr: "domuz eti", lvl: "A1", cat: "Yiyecek" },
{ en: "possible", tr: "mümkün", lvl: "A2", cat: "Sıfat" },
{ en: "possibly", tr: "muhtemelen", lvl: "A2", cat: "Zarf" },
{ en: "post office", tr: "posta ofisi", lvl: "A1", cat: "Yer" },
{ en: "postcard", tr: "kartpostal", lvl: "A1", cat: "Nesne" },
{ en: "pot", tr: "tencere", lvl: "A1", cat: "Nesne" },
{ en: "potato", tr: "patates", lvl: "A1", cat: "Yiyecek" },
{ en: "power", tr: "güç / enerji", lvl: "A2", cat: "Soyut Kavram" },
{ en: "practice", tr: "pratik yapmak", lvl: "A2", cat: "Fiil" },
{ en: "prepare", tr: "hazırlamak", lvl: "A2", cat: "Fiil" },
{ en: "preposition", tr: "edat", lvl: "A2", cat: "Dilbilgisi" },
{ en: "press", tr: "basmak / basın", lvl: "A2", cat: "Fiil / İsim" },
{ en: "price", tr: "fiyat", lvl: "A1", cat: "Nesne" },
{ en: "priest", tr: "papaz", lvl: "A2", cat: "Meslek" },
{ en: "private", tr: "özel", lvl: "A2", cat: "Sıfat" },
{ en: "probably", tr: "muhtemelen", lvl: "A2", cat: "Zarf" },
{ en: "problem", tr: "sorun", lvl: "A1", cat: "Soyut Kavram" },
{ en: "produce", tr: "üretmek", lvl: "A2", cat: "Fiil" },
{ en: "profit", tr: "kâr", lvl: "A2", cat: "Soyut Kavram" },
{ en: "programme", tr: "program", lvl: "A2", cat: "İsim" },
{ en: "project", tr: "proje", lvl: "A2", cat: "İsim" },
{ en: "pronounce", tr: "telaffuz etmek", lvl: "A2", cat: "Fiil" },
{ en: "proud", tr: "gururlu", lvl: "A2", cat: "Duygu" },
{ en: "public", tr: "kamu / halka açık", lvl: "A2", cat: "Sıfat" },
{ en: "pull", tr: "çekmek", lvl: "A1", cat: "Fiil" },
{ en: "pullover", tr: "kazak", lvl: "A1", cat: "Giyim" },
{ en: "puppy", tr: "yavru köpek", lvl: "A1", cat: "Hayvan" },
{ en: "purpose", tr: "amaç", lvl: "A2", cat: "Soyut Kavram" },
{ en: "push", tr: "itmek", lvl: "A1", cat: "Fiil" },
{ en: "put", tr: "koymak", lvl: "A1", cat: "Fiil" },

// Q
{ en: "quality", tr: "kalite", lvl: "A2", cat: "Soyut Kavram" },
{ en: "quarter", tr: "çeyrek", lvl: "A2", cat: "Soyut Kavram / Zaman" },
{ en: "question", tr: "soru", lvl: "A1", cat: "Soyut Kavram" },
{ en: "quick", tr: "hızlı", lvl: "A1", cat: "Sıfat" },
{ en: "quickly", tr: "hızlıca", lvl: "A1", cat: "Zarf" },

// R
{ en: "radio", tr: "radyo", lvl: "A1", cat: "Eşya" },
{ en: "rain", tr: "yağmur", lvl: "A1", cat: "Doğa" },
{ en: "raincoat", tr: "yağmurluk", lvl: "A2", cat: "Kıyafet" },
{ en: "rainy", tr: "yağmurlu", lvl: "A2", cat: "Sıfat" },
{ en: "rather", tr: "daha doğrusu", lvl: "B1", cat: "Zarf" },
{ en: "reach", tr: "ulaşmak", lvl: "A2", cat: "Fiil" },
{ en: "read", tr: "okumak", lvl: "A1", cat: "Fiil" },
{ en: "reader", tr: "okuyucu", lvl: "A2", cat: "İsim" },
{ en: "ready", tr: "hazır", lvl: "A1", cat: "Sıfat" },
{ en: "real", tr: "gerçek", lvl: "A2", cat: "Sıfat" },
{ en: "really", tr: "gerçekten", lvl: "A1", cat: "Zarf" },
{ en: "reason", tr: "sebep", lvl: "A2", cat: "İsim" },
{ en: "reasonable", tr: "makul", lvl: "B1", cat: "Sıfat" },
{ en: "receive", tr: "almak", lvl: "A2", cat: "Fiil" },
{ en: "record", tr: "kayıt / kaydetmek", lvl: "A2", cat: "İsim / Fiil" },
{ en: "red", tr: "kırmızı", lvl: "A1", cat: "Renk" },
{ en: "referee", tr: "hakem", lvl: "A2", cat: "İsim" },
{ en: "refuse", tr: "reddetmek", lvl: "A2", cat: "Fiil" },
{ en: "remember", tr: "hatırlamak", lvl: "A1", cat: "Fiil" },
{ en: "remind", tr: "hatırlatmak", lvl: "A2", cat: "Fiil" },
{ en: "report", tr: "rapor / bildirmek", lvl: "A2", cat: "İsim / Fiil" },
{ en: "rest", tr: "dinlenmek / dinlenme", lvl: "A1", cat: "Fiil / İsim" },
{ en: "result", tr: "sonuç", lvl: "A2", cat: "İsim" },
{ en: "rich", tr: "zengin", lvl: "A2", cat: "Sıfat" },
{ en: "right", tr: "doğru / sağ", lvl: "A1", cat: "Sıfat / İsim" },
{ en: "rang", tr: "çalmak (geçmiş zaman)", lvl: "A2", cat: "Fiil" },
{ en: "ring", tr: "çan / yüzük / aramak", lvl: "A2", cat: "İsim / Fiil" },
{ en: "risk", tr: "risk", lvl: "A2", cat: "İsim" },
{ en: "road", tr: "yol", lvl: "A1", cat: "Yer" },
{ en: "room", tr: "oda", lvl: "A1", cat: "Yer" },
{ en: "ruler", tr: "cetvel / yönetici", lvl: "A2", cat: "Eşya / İnsan" },
{ en: "run", tr: "koşmak", lvl: "A1", cat: "Fiil" },

// S
{ en: "sad", tr: "üzgün", lvl: "A1", cat: "Duygu" },
{ en: "salad", tr: "salata", lvl: "A1", cat: "Yiyecek" },
{ en: "salary", tr: "maaş", lvl: "A2", cat: "Soyut Kavram" },
{ en: "same", tr: "aynı", lvl: "A1", cat: "Sıfat" },
{ en: "saturday", tr: "cumartesi", lvl: "A1", cat: "Zaman" },
{ en: "say", tr: "söylemek", lvl: "A1", cat: "Fiil" },
{ en: "school", tr: "okul", lvl: "A1", cat: "Yer" },
{ en: "science", tr: "bilim", lvl: "A2", cat: "Soyut Kavram" },
{ en: "sea", tr: "deniz", lvl: "A1", cat: "Doğa" },
{ en: "season", tr: "mevsim", lvl: "A1", cat: "Zaman" },
{ en: "seat", tr: "koltuk", lvl: "A1", cat: "Eşya" },
{ en: "second", tr: "ikinci / saniye", lvl: "A1", cat: "Zaman / Sıfat" },
{ en: "see", tr: "görmek", lvl: "A1", cat: "Fiil" },
{ en: "seem", tr: "görünmek", lvl: "A2", cat: "Fiil" },
{ en: "sell", tr: "satmak", lvl: "A1", cat: "Fiil" },
{ en: "send", tr: "göndermek", lvl: "A1", cat: "Fiil" },
{ en: "sentence", tr: "cümle", lvl: "A1", cat: "Soyut Kavram" },
{ en: "september", tr: "eylül", lvl: "A1", cat: "Zaman" },
{ en: "serve", tr: "hizmet etmek / servis yapmak", lvl: "A2", cat: "Fiil" },
{ en: "service", tr: "hizmet", lvl: "A2", cat: "Soyut Kavram" },
{ en: "set", tr: "ayarlamak / set", lvl: "A2", cat: "Fiil / İsim" },
{ en: "several", tr: "birkaç", lvl: "A2", cat: "Sıfat" },
{ en: "sex", tr: "cinsiyet", lvl: "A2", cat: "Soyut Kavram" },
{ en: "shall", tr: "–meli / –malı", lvl: "B1", cat: "Yardımcı Fiil" },
{ en: "she", tr: "o (kadın)", lvl: "A1", cat: "Zamir" },
{ en: "shop", tr: "dükkan", lvl: "A1", cat: "Yer" },
{ en: "shopkeeper", tr: "dükkan sahibi", lvl: "A2", cat: "İnsan" },
{ en: "short", tr: "kısa", lvl: "A1", cat: "Sıfat" },
{ en: "should", tr: "–meli / –malı", lvl: "B1", cat: "Yardımcı Fiil" },
{ en: "show", tr: "göstermek", lvl: "A1", cat: "Fiil" },
{ en: "shut", tr: "kapamak", lvl: "A1", cat: "Fiil" },
{ en: "sick", tr: "hasta", lvl: "A1", cat: "Sıfat" },
{ en: "side", tr: "yan", lvl: "A1", cat: "Yer / Soyut Kavram" },
{ en: "simple", tr: "basit", lvl: "A1", cat: "Sıfat" },
{ en: "since", tr: "–den beri", lvl: "A2", cat: "Edat / Bağlaç" },
{ en: "sing", tr: "şarkı söylemek", lvl: "A1", cat: "Fiil" },
{ en: "singer", tr: "şarkıcı", lvl: "A1", cat: "İnsan" },
{ en: "single", tr: "bekar / tek", lvl: "A2", cat: "Sıfat" },
{ en: "sister", tr: "kız kardeş", lvl: "A1", cat: "İnsan" },
{ en: "sit", tr: "oturmak", lvl: "A1", cat: "Fiil" },
{ en: "size", tr: "beden / boyut", lvl: "A1", cat: "Soyut Kavram" },
{ en: "ski", tr: "kayak yapmak / kayak", lvl: "A2", cat: "Fiil / İsim" },
{ en: "sleep", tr: "uyumak", lvl: "A1", cat: "Fiil" },
{ en: "small", tr: "küçük", lvl: "A1", cat: "Sıfat" },
{ en: "so", tr: "bu yüzden / öyle", lvl: "A1", cat: "Bağlaç / Zarf" },
{ en: "soccer", tr: "futbol", lvl: "A1", cat: "Spor" },
{ en: "society", tr: "toplum", lvl: "A2", cat: "Soyut Kavram" },
{ en: "sock", tr: "çorap", lvl: "A1", cat: "Kıyafet" },
{ en: "soft", tr: "yumuşak", lvl: "A1", cat: "Sıfat" },
{ en: "some", tr: "birkaç / biraz", lvl: "A1", cat: "Sıfat / Zarf" },
{ en: "somebody", tr: "biri", lvl: "A1", cat: "Zamir" },
{ en: "someone", tr: "biri", lvl: "A1", cat: "Zamir" },
{ en: "something", tr: "bir şey", lvl: "A1", cat: "Zamir" },
{ en: "sometimes", tr: "bazen", lvl: "A1", cat: "Zarf" },
{ en: "somewhere", tr: "bir yer", lvl: "A1", cat: "Zamir" },
{ en: "son", tr: "oğul", lvl: "A1", cat: "İnsan" },
{ en: "soon", tr: "yakında", lvl: "A1", cat: "Zarf" },
{ en: "sorry", tr: "üzgünüm / pardon", lvl: "A1", cat: "Duygu" },
{ en: "sound", tr: "ses", lvl: "A1", cat: "Soyut Kavram" },
{ en: "south", tr: "güney", lvl: "A1", cat: "Yer / Yön" },
{ en: "speak", tr: "konuşmak", lvl: "A1", cat: "Fiil" },
{ en: "special", tr: "özel", lvl: "A1", cat: "Sıfat" },
{ en: "speed", tr: "hız", lvl: "A1", cat: "Soyut Kavram" },
{ en: "spend", tr: "harcamak / geçirmek", lvl: "A1", cat: "Fiil" },
{ en: "spoon", tr: "kaşık", lvl: "A1", cat: "Eşya" },
{ en: "sport", tr: "spor", lvl: "A1", cat: "Spor" },
{ en: "spring", tr: "ilkbahar / yay", lvl: "A1", cat: "Zaman / Nesne" },
{ en: "stairs", tr: "merdiven", lvl: "A1", cat: "Eşya" },
{ en: "stamp", tr: "pul", lvl: "A1", cat: "Eşya" },
{ en: "stand", tr: "ayakta durmak", lvl: "A1", cat: "Fiil" },
{ en: "stand up", tr: "ayağa kalkmak", lvl: "A1", cat: "Fiil" },
{ en: "station", tr: "istasyon / durak", lvl: "A1", cat: "Yer" },
{ en: "stay", tr: "kalmak", lvl: "A1", cat: "Fiil" },
{ en: "still", tr: "hala / sessiz", lvl: "A1", cat: "Zarf / Sıfat" },
{ en: "stop", tr: "durmak / durdurmak", lvl: "A1", cat: "Fiil" },
{ en: "street", tr: "sokak", lvl: "A1", cat: "Yer" },
{ en: "strong", tr: "güçlü", lvl: "A1", cat: "Sıfat" },
{ en: "student", tr: "öğrenci", lvl: "A1", cat: "İnsan" },
{ en: "success", tr: "başarı", lvl: "A2", cat: "Soyut Kavram" },
{ en: "such", tr: "böyle / çok", lvl: "A1", cat: "Sıfat" },
{ en: "suddenly", tr: "aniden", lvl: "A1", cat: "Zarf" },
{ en: "summer", tr: "yaz", lvl: "A1", cat: "Zaman" },
{ en: "sun", tr: "güneş", lvl: "A1", cat: "Doğa" },
{ en: "sunday", tr: "pazar", lvl: "A1", cat: "Zaman" },
{ en: "sunflower", tr: "günebakan", lvl: "A1", cat: "Doğa" },
{ en: "sunglasses", tr: "güneş gözlüğü", lvl: "A1", cat: "Kıyafet" },
{ en: "sunlight", tr: "güneş ışığı", lvl: "A1", cat: "Doğa" },
{ en: "sunny", tr: "güneşli", lvl: "A1", cat: "Sıfat" },
{ en: "sunrise", tr: "gün doğumu", lvl: "A2", cat: "Doğa" },
{ en: "sure", tr: "emin", lvl: "A1", cat: "Sıfat" },
{ en: "sweater", tr: "kazak", lvl: "A1", cat: "Kıyafet" },
{ en: "swim", tr: "yüzmek", lvl: "A1", cat: "Fiil" },
{ en: "swimmer", tr: "yüzücü", lvl: "A1", cat: "İnsan" },
{ en: "system", tr: "sistem", lvl: "A2", cat: "Soyut Kavram" },

// T
{ en: "table", tr: "masa", lvl: "A1", cat: "Eşya" },
{ en: "table tennis", tr: "masa tenisi", lvl: "A1", cat: "Spor" },
{ en: "take", tr: "almak", lvl: "A1", cat: "Fiil" },
{ en: "talk", tr: "konuşmak", lvl: "A1", cat: "Fiil" },
{ en: "tap", tr: "dokunmak / musluk", lvl: "A2", cat: "Fiil / Eşya" },
{ en: "tax", tr: "vergi", lvl: "A2", cat: "Soyut Kavram" },
{ en: "taxi", tr: "taksi", lvl: "A1", cat: "Ulaşım" },
{ en: "tea", tr: "çay", lvl: "A1", cat: "İçecek" },
{ en: "teach", tr: "öğretmek", lvl: "A1", cat: "Fiil" },
{ en: "teacher", tr: "öğretmen", lvl: "A1", cat: "İnsan" },
{ en: "team", tr: "takım", lvl: "A1", cat: "Soyut Kavram" },
{ en: "teapot", tr: "çaydanlık", lvl: "A1", cat: "Eşya" },
{ en: "telegraph", tr: "telgraf", lvl: "B1", cat: "İletişim" },
{ en: "telephone", tr: "telefon", lvl: "A1", cat: "İletişim" },
{ en: "television", tr: "televizyon", lvl: "A1", cat: "Eşya" },
{ en: "tell", tr: "anlatmak / söylemek", lvl: "A1", cat: "Fiil" },
{ en: "temperature", tr: "sıcaklık", lvl: "A1", cat: "Soyut Kavram" },
{ en: "test", tr: "test / sınav", lvl: "A1", cat: "Soyut Kavram" },
{ en: "textbook", tr: "ders kitabı", lvl: "A1", cat: "Eşya" },
{ en: "than", tr: "–den / –dan", lvl: "A2", cat: "Bağlaç" },
{ en: "thank", tr: "teşekkür etmek", lvl: "A1", cat: "Fiil" },
{ en: "thanks", tr: "teşekkürler", lvl: "A1", cat: "Deyim / İfade" },
{ en: "that", tr: "şu / ki", lvl: "A1", cat: "Zamir / Bağlaç" },
{ en: "the", tr: "belirli tanımlık", lvl: "A1", cat: "Dilbilgisi" },
{ en: "theatre", tr: "tiyatro", lvl: "A1", cat: "Yer" },
{ en: "their", tr: "onların", lvl: "A1", cat: "Zamir" },
{ en: "theirs", tr: "onlarınki", lvl: "A1", cat: "Zamir" },
{ en: "them", tr: "onları / onlara", lvl: "A1", cat: "Zamir" },
{ en: "themselves", tr: "kendileri", lvl: "A2", cat: "Zamir" },
{ en: "then", tr: "o zaman / sonra", lvl: "A1", cat: "Zarf" },
{ en: "there", tr: "orada", lvl: "A1", cat: "Zarf" },
{ en: "these", tr: "bunlar", lvl: "A1", cat: "Zamir" },
{ en: "they", tr: "onlar", lvl: "A1", cat: "Zamir" },
{ en: "thing", tr: "şey", lvl: "A1", cat: "Soyut Kavram" },
{ en: "think", tr: "düşünmek", lvl: "A1", cat: "Fiil" },
{ en: "third", tr: "üçüncü", lvl: "A1", cat: "Sıfat / Sıra" },
{ en: "this", tr: "bu", lvl: "A1", cat: "Zamir" },
{ en: "those", tr: "şunlar", lvl: "A1", cat: "Zamir" },
{ en: "through", tr: "boyunca / içinden", lvl: "A2", cat: "Edat" },
{ en: "throw", tr: "atmak", lvl: "A1", cat: "Fiil" },
{ en: "thursday", tr: "perşembe", lvl: "A1", cat: "Zaman" },
{ en: "ticket", tr: "bilet", lvl: "A1", cat: "Eşya" },
{ en: "time", tr: "zaman", lvl: "A1", cat: "Soyut Kavram" },
{ en: "tired", tr: "yorgun", lvl: "A1", cat: "Sıfat" },
{ en: "to", tr: "–e / –a", lvl: "A1", cat: "Edat" },
{ en: "today", tr: "bugün", lvl: "A1", cat: "Zaman" },
{ en: "toe", tr: "ayak parmağı", lvl: "A1", cat: "Vücut" },
{ en: "together", tr: "birlikte", lvl: "A1", cat: "Zarf" },
{ en: "tomorrow", tr: "yarın", lvl: "A1", cat: "Zaman" },
{ en: "tonight", tr: "bu akşam", lvl: "A1", cat: "Zaman" },
{ en: "too", tr: "çok / ayrıca", lvl: "A1", cat: "Zarf" },
{ en: "tooth", tr: "diş", lvl: "A1", cat: "Vücut" },
{ en: "toothache", tr: "diş ağrısı", lvl: "A1", cat: "Sağlık" },
{ en: "toothbrush", tr: "diş fırçası", lvl: "A1", cat: "Eşya" },
{ en: "toothpaste", tr: "diş macunu", lvl: "A1", cat: "Eşya" },
{ en: "top", tr: "üst / tepe", lvl: "A1", cat: "Sıfat / Yer" },
{ en: "total", tr: "toplam", lvl: "A1", cat: "Sıfat" },
{ en: "towards", tr: "–e doğru", lvl: "A2", cat: "Edat" },
{ en: "town", tr: "kasaba / şehir", lvl: "A1", cat: "Yer" },
{ en: "toy", tr: "oyuncak", lvl: "A1", cat: "Eşya" },
{ en: "traffic", tr: "trafik", lvl: "A2", cat: "Soyut Kavram" },
{ en: "train", tr: "tren", lvl: "A1", cat: "Ulaşım" },
{ en: "tray", tr: "tepsi", lvl: "A1", cat: "Eşya" },
{ en: "tree", tr: "ağaç", lvl: "A1", cat: "Doğa" },
{ en: "trouble", tr: "sorun / belâ", lvl: "A2", cat: "Soyut Kavram" },
{ en: "be in trouble", tr: "başı belada olmak", lvl: "A2", cat: "İfade" },
{ en: "get into trouble", tr: "başını belaya sokmak", lvl: "A2", cat: "İfade" },
{ en: "true", tr: "doğru / gerçek", lvl: "A1", cat: "Sıfat" },
{ en: "truth", tr: "gerçek", lvl: "A1", cat: "Soyut Kavram" },
{ en: "try", tr: "denemek", lvl: "A1", cat: "Fiil" },
{ en: "tuesday", tr: "salı", lvl: "A1", cat: "Zaman" },
{ en: "turn", tr: "dönmek / çevirmek", lvl: "A1", cat: "Fiil" },
{ en: "turn off", tr: "kapamak", lvl: "A1", cat: "Fiil" },
{ en: "turn on", tr: "açmak", lvl: "A1", cat: "Fiil" },
{ en: "tv", tr: "televizyon", lvl: "A1", cat: "Eşya" },
{ en: "twice", tr: "iki kez", lvl: "A1", cat: "Zarf" },

// U
{ en: "ugly", tr: "çirkin", lvl: "A1", cat: "Sıfat" },
{ en: "umbrella", tr: "şemsiye", lvl: "A1", cat: "Eşya" },
{ en: "under", tr: "altında", lvl: "A1", cat: "Edat / Zarf" },
{ en: "underground", tr: "yeraltı / metro", lvl: "A1", cat: "Yer / Ulaşım" },
{ en: "understand", tr: "anlamak", lvl: "A1", cat: "Fiil" },
{ en: "until", tr: "kadar", lvl: "A1", cat: "Edat" },
{ en: "up", tr: "yukarı", lvl: "A1", cat: "Zarf / Yön" },
{ en: "us", tr: "bizi / bize", lvl: "A1", cat: "Zamir" },
{ en: "use", tr: "kullanmak", lvl: "A1", cat: "Fiil" },
{ en: "useful", tr: "yararlı / faydalı", lvl: "A1", cat: "Sıfat" },
{ en: "usually", tr: "genellikle", lvl: "A1", cat: "Zarf" },

// V
{ en: "vase", tr: "vazo", lvl: "A1", cat: "Eşya" },
{ en: "verb", tr: "fiil", lvl: "A1", cat: "Dilbilgisi" },
{ en: "very", tr: "çok / oldukça", lvl: "A1", cat: "Zarf" },
{ en: "video", tr: "video", lvl: "A1", cat: "Eşya / Medya" },
{ en: "view", tr: "manzara / görmek", lvl: "A2", cat: "İsim / Fiil" },
{ en: "village", tr: "köy", lvl: "A2", cat: "Yer" },

// W
{ en: "wait", tr: "beklemek", lvl: "A1", cat: "Fiil" },
{ en: "waiter", tr: "garson (erkek)", lvl: "A1", cat: "Meslek" },
{ en: "waitress", tr: "garson (kadın)", lvl: "A1", cat: "Meslek" },
{ en: "walk", tr: "yürümek", lvl: "A1", cat: "Fiil" },
{ en: "wall", tr: "duvar", lvl: "A1", cat: "Eşya / Yer" },
{ en: "want", tr: "istemek", lvl: "A1", cat: "Fiil" },
{ en: "warm", tr: "ılık / sıcak", lvl: "A1", cat: "Sıfat" },
{ en: "was", tr: "idi / oldu", lvl: "A1", cat: "Fiil" },
{ en: "wash", tr: "yıkamak", lvl: "A1", cat: "Fiil" },
{ en: "watch", tr: "izlemek / saat", lvl: "A1", cat: "Fiil / Eşya" },
{ en: "water", tr: "su", lvl: "A1", cat: "İçecek" },
{ en: "watermelon", tr: "karpuz", lvl: "A1", cat: "Meyve" },
{ en: "way", tr: "yol / şekilde", lvl: "A1", cat: "İsim" },
{ en: "we", tr: "biz", lvl: "A1", cat: "Zamir" },
{ en: "wear", tr: "giymek", lvl: "A1", cat: "Fiil" },
{ en: "weather", tr: "hava durumu", lvl: "A1", cat: "Doğa" },
{ en: "wednesday", tr: "çarşamba", lvl: "A1", cat: "Zaman" },
{ en: "week", tr: "hafta", lvl: "A1", cat: "Zaman" },
{ en: "weekend", tr: "hafta sonu", lvl: "A1", cat: "Zaman" },
{ en: "weight", tr: "ağırlık", lvl: "A2", cat: "İsim" },
{ en: "well", tr: "iyi / kuyu", lvl: "A1", cat: "Sıfat / İsim" },
{ en: "what", tr: "ne", lvl: "A1", cat: "Soru Zamiri" },
{ en: "when", tr: "ne zaman", lvl: "A1", cat: "Soru Zamiri" },
{ en: "where", tr: "nerede", lvl: "A1", cat: "Soru Zamiri" },
{ en: "which", tr: "hangi", lvl: "A1", cat: "Soru Zamiri" },
{ en: "whistle", tr: "ıslık", lvl: "A2", cat: "İsim" },
{ en: "white", tr: "beyaz", lvl: "A1", cat: "Renk" },
{ en: "who", tr: "kim", lvl: "A1", cat: "Soru Zamiri" },
{ en: "whole", tr: "bütün", lvl: "A2", cat: "Sıfat" },
{ en: "whom", tr: "kimi / kime", lvl: "B1", cat: "Soru Zamiri" },
{ en: "whose", tr: "kimin", lvl: "B1", cat: "Soru Zamiri" },
{ en: "why", tr: "neden", lvl: "A1", cat: "Soru Zamiri" },
{ en: "wide", tr: "geniş", lvl: "A2", cat: "Sıfat" },
{ en: "wife", tr: "eş (kadın)", lvl: "A1", cat: "İnsan" },
{ en: "will", tr: "istek / -ecek", lvl: "A1", cat: "Fiil / Yardımcı Fiil" },
{ en: "will you", tr: "yapacak mısın?", lvl: "A1", cat: "Soru İfadesi" },
{ en: "win", tr: "kazanmak", lvl: "A1", cat: "Fiil" },
{ en: "window", tr: "pencere", lvl: "A1", cat: "Eşya / Yer" },
{ en: "windy", tr: "rüzgarlı", lvl: "A1", cat: "Sıfat" },
{ en: "winter", tr: "kış", lvl: "A1", cat: "Zaman / Mevsim" },
{ en: "wish", tr: "dilemek", lvl: "A1", cat: "Fiil" },
{ en: "with", tr: "ile", lvl: "A1", cat: "Edat" },
{ en: "without", tr: "olmadan", lvl: "A1", cat: "Edat" },
{ en: "woman", tr: "kadın", lvl: "A1", cat: "İnsan" },
{ en: "wonderful", tr: "harika", lvl: "A1", cat: "Sıfat" },
{ en: "word", tr: "kelime", lvl: "A1", cat: "İsim" },
{ en: "work", tr: "çalışmak / iş", lvl: "A1", cat: "Fiil / İsim" },
{ en: "workman", tr: "işçi", lvl: "A2", cat: "Meslek" },
{ en: "world", tr: "dünya", lvl: "A1", cat: "Yer / İsim" },
{ en: "worry", tr: "endişelenmek", lvl: "A1", cat: "Fiil" },
{ en: "write", tr: "yazmak", lvl: "A1", cat: "Fiil" },
{ en: "wrong", tr: "yanlış", lvl: "A1", cat: "Sıfat" },

// Y
{ en: "year", tr: "yıl", lvl: "A1", cat: "Zaman" },
{ en: "yellow", tr: "sarı", lvl: "A1", cat: "Renk" },
{ en: "yes", tr: "evet", lvl: "A1", cat: "Kelime / Onay" },
{ en: "yesterday", tr: "dün", lvl: "A1", cat: "Zaman" },
{ en: "yet", tr: "henüz / daha", lvl: "A2", cat: "Zamir / Bağlaç" },
{ en: "yoghurt", tr: "yoğurt", lvl: "A1", cat: "Yiyecek" },
{ en: "you", tr: "sen / siz", lvl: "A1", cat: "Zamir" },
{ en: "young", tr: "genç", lvl: "A1", cat: "Sıfat" },
{ en: "your", tr: "senin / sizin", lvl: "A1", cat: "Zamir" },
{ en: "yours", tr: "seninki / sizinki", lvl: "A1", cat: "Zamir" },
{ en: "yourself", tr: "kendin / kendiniz", lvl: "A1", cat: "Zamir" },

// Z
{ en: "zero", tr: "sıfır", lvl: "A1", cat: "Sayı" },
{ en: "zoo", tr: "hayvanat bahçesi", lvl: "A1", cat: "Yer" }



];